version: '3.8'

services:
  web:
    #　ベースイメージイメージの設定
    image: php:8.2-apache
    container_name: lamp-web
    #apacheのデフォルトポート80にローカルのポート8080をマッピング
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
     #LAMP環境の典型的な用途は、PHPでデータベース（MySQL）を読み書きするであるため
      - db

  db:
    image: mysql:8.0
    container_name: lamp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
  db_data:
